### ISSUE TITLE
if и else всегда используются с круглыми скобками

### ISSUE THREAD

**Issue by coursar** [mazaytsev/Java-Practice#4]
https://github.com/mazaytsev/Java-Practice/blob/40d651583040847b9e09de8ebea50fd86e72de6f/src/main/java/homework/task1/Service.java#L8-L9

**Comment by mazaytsev** [comment]
@coursar немного не понял топик. Вы имеете ввиду, что нужно добавить фигурные скобки к блокам условного оператора?

**Comment by coursar** [comment]
Да, фигурные, не круглые
